version: "3.9"

services:

  backend:
    build: ./backend
    entrypoint: ["/app/startup.sh"]
    ports:
      - 8000:8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=myresolver
      - traefik.http.services.api.loadbalancer.server.port=8000

    depends_on:
      - db
    volumes:
      - ./backend/app:/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "50"
    env_file:
      - .env
    networks:
      - network1

  frontend:
    build:
      context: ./frontend
      target: production-stage
    restart: always
    environment:
      - HOST=${HOST}
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "50"
    networks:
      - network1
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=myresolver
      - traefik.http.services.frontend.loadbalancer.server.port=80

  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "50"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - network1

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - network1

  traefik:
    image: traefik:2.10
    command:
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=george.strakhov@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/acme.json
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "50"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    networks:
      - network1

networks:
  network1:

volumes:
  redis_data:
