# Generated by Django 5.0.1 on 2024-01-28 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('q_id', models.CharField(db_index=True, max_length=255)),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('stopped', 'STOPPED')], default='running', max_length=50)),
                ('progress_report', models.TextField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('func_name', models.CharField(blank=True, max_length=255, null=True)),
                ('input', models.TextField(blank=True, null=True)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
